export const CITIES_LIST = [
  "Abşeron",
  "Ağcabədi",
  "Ağdam",
  "Ağdaş",
  "Ağstafa",
  "Ağsu",
  "Astara",
  "Babək",
  "Bakı",
  "Balakən",
  "Bərdə",
  "Beyləqan",
  "Biləsuvar",
  "Cəbrayıl",
  "Cəlilabad",
  "Culfa",
  "Daşkəsən",
  "Füzuli",
  "Gədəbəy",
  "Gəncə",
  "Goranboy",
  "Göyçay",
  "Göygöl",
  "Hacıqabul",
  "İmişli",
  "İsmayıllı",
  "Kəlbəcər",
  "Kəngərli",
  "Kürdəmir",
  "Laçın",
  "Lənkəran",
  "Lerik",
  "Masallı",
  "Mingəçevir",
  "Naftalan",
  "Naxçıvan",
  "Neftçala",
  "Oğuz",
  "Ordubad",
  "Qax",
  "Qazax",
  "Qəbələ",
  "Qobustan",
  "Quba",
  "Qubadlı",
  "Qusar",
  "Saatlı",
  "Sabirabad",
  "Salyan",
  "Samux",
  "Sədərək",
  "Siyəzən",
  "Sumqayıt",
  "Şabran",
  "Şahbuz",
  "Şamaxı",
  "Şəki",
  "Şəmkir",
  "Şərur",
  "Şirvan",
  "Şuşa",
  "Tərtər",
  "Tovuz",
  "Ucar",
  "Xaçmaz",
  "Xankəndi",
  "Xırdalan",
  "Xızı",
  "Xocalı",
  "Xocavənd",
  "Yardımlı",
  "Yevlax",
  "Zaqatala",
  "Zəngilan",
  "Zərdab",
];

export const BRAND_LIST = [
  "Apple",
  "Samsung",
  "Huawei",
  "Xiaomi",
  "Oppo",
  "Vivo",
  "OnePlus",
  "Google",
  "LG",
  "Sony",
  "Motorola",
  "Nokia",
  "HTC",
  "Lenovo",
  "Asus",
  "BlackBerry",
  "Realme",
  "ZTE",
  "Alcatel",
  "Meizu",
  "Panasonic",
  "Honor",
  "Infinix",
  "Gionee",
  "Micromax",
  "Lava",
  "Symphony",
  "Wiko",
  "TCL",
  "Vertu",
  "Motorola",
  "Vodafone",
  "Sanyo",
  "Xolo",
  "Karbonn",
  "Spice",
  "Maxx",
];

export const Phone_Memory_List = [
  "16 GB",
  "32 GB",
  "64 GB",
  "128 GB",
  "256 GB",
  "512 GB",
  "1 TB",
];

export const CardMockData = [
  {
    id: 1,
    imgPath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGMr4p8Wm_4i1yY3bEbUuUz32fof5k4ENrL3tcEuAlNAmXl_E43qrSSRFyvOIdjmLXeOU&usqp=CAU",
    price: "290 AZN",
    brand: "Iphone",
    model: "14 Pro Max",
    country: "Azerbaijan",
    city: "Baku",
    number: 555322312,
    date: "12 Sentyabr 2023",
  },
  {
    id: 2,
    imgPath:
      "https://www.digitaltrends.com/wp-content/uploads/2022/08/iPhone-SE-2022-Starlight-Back-in-Hand.jpg?p=1",
    price: "290 AZN",
    brand: "BlackBerry",
    model: "Unknown",
    country: "Azerbaijan",
    city: "Baku",
    number: 513542312,
    date: "23 Oktyabr 2023",
  },
  {
    id: 3,
    imgPath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS38ka6n4SJwKxXzgkI3wkTAYaNkTY0z3GhCy7J8ILz7wVz5HzZ-VG60wEymFygWO77dRw&usqp=CAU",
    price: "4567 AZN",
    brand: "Samsung",
    model: "A52",
    country: "Azerbaijan",
    city: "Baku",
    number: 506532312,
    date: "21 Dekabr 2023",
  },
  {
    id: 4,
    imgPath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS38ka6n4SJwKxXzgkI3wkTAYaNkTY0z3GhCy7J8ILz7wVz5HzZ-VG60wEymFygWO77dRw&usqp=CAU",
    price: "4567 AZN",
    brand: "Samsung",
    model: "A52",
    country: "Azerbaijan",
    city: "Baku",
    number: 506532312,
    date: "21 Dekabr 2023",
  },
  {
    id: 5,
    imgPath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS38ka6n4SJwKxXzgkI3wkTAYaNkTY0z3GhCy7J8ILz7wVz5HzZ-VG60wEymFygWO77dRw&usqp=CAU",
    price: "4567 AZN",
    brand: "Samsung",
    model: "A52",
    country: "Azerbaijan",
    city: "Baku",
    number: 506532312,
    date: "21 Dekabr 2023",
  },

  {
    id: 6,
    imgPath:
      "https://www.apple.com/newsroom/images/product/iphone/standard/Apple-iPhone-14-iPhone-14-Plus-hero-220907_Full-Bleed-Image.jpg.large.jpg",
    price: "2345 AZN",
    brand: "Iphone",
    model: "13 Pro Max",
    country: "Azerbaijan",
    city: "Baku",
    number: 101232312,
    date: "20 Yanvar 2022",
  },
];
